name: CI
on: [push]

jobs:
  build-gcc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - run: sudo apt install graphviz python3-dev libgraphviz-dev python3-pip python3-setuptools libboost-all-dev
      - run: pip3 install xmlrunner pygraphviz pygraphml
      - run: mkdir build
      - run: cmake -B build
      - run: make  -C build VERBOSE=1
